### ISSUE TITLE
Developed model for weekly email recommendation roster

### ISSUE THREAD

**Issue by ShanmukhaSreenivas** [nikki1234567/MovieRecommender#10]
Created a model to generate weekly email movie recommendations based on weighted plot similarity.

**Comment by nikki1234567** [comment]
The model is working well for generating personalized recommendations. Next, we should ensure the weekly email scheduling and user opt-in functionality are fully integrated, so subscribed users receive these recommendations on schedule

**Comment by ShanmukhaSreenivas** [comment]
The weekly email recommendation model has been successfully developed. It analyzes users' recommended movie history, applying a weighted plot-based approach using the frequency of each movie as a weight, and utilizes cosine similarity to find plot-similar movies. Users who opted in at registration will receive these tailored recommendations weekly.

Commit ID's : c4dfc7987206cab092b382dc0b8dccda8aa37c17, ac851c6f02711f8bb0cfe637a7c400e9ae0e7b24
