### ISSUE TITLE
Fix the UI for register and login pages

### ISSUE THREAD

**Issue by ShanmukhaSreenivas** [nikki1234567/MovieRecommender#5]
Improved the UI for the register and login pages for a better user experience.

**Comment by mohithn75** [comment]
Login file: Enhanced form validation, updated error messages, and improved mobile responsiveness.
Register file: Simplified registration flow, added password strength indicator, and optimized field layout.

login file commit ID: 61547d56836b234151c9e9ce50a4bbfa7daf204c
Register file commit ID: cded1dce071344cab4a68d15e31c23430886dd96
