### ISSUE TITLE
History and Success pages's UI and functionality

### ISSUE THREAD

**Issue by ShanmukhaSreenivas** [nikki1234567/MovieRecommender#7]
Update UI and improved functionality on history and success pages.

**Comment by mohithn75** [comment]
History File: Streamlined content structure, added recent project milestones, and updated with current development phases.
Success File: Highlighted key achievements, added user feedback summaries, and improved readability.

History file commit ID : cb6e1a182f42b4450f8f0a150363cc43e6a930f2
Success File commit ID: 4a245bd559b8d7fe48c3d13d3f1ee9c33e0540b8
